name: Lint_and_Test

on:
  push:
    paths:
      - "**/*.go"
      - "go.mod"

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: golangci/golangci-lint-action@v3
      - run: go test ./...
